### ISSUE TITLE
Basic interactions

### ISSUE THREAD

**Issue by gogo1704** [gogo1704/furry-bot#12]
Fajnie byłoby żeby było dużo prostych poleceń typu ;shoot, ;hug, ;gay. Pozwoli to na fajne interakcje. Można by zrobić całkowicie osobny model komendy.

**Comment by BrzesiekGrydniak** [comment]
To jest zadanie do zrobienia w krótkim czasie zależnego tylko i wyłącznie od ilości tych poleceń bo napisanie jednego to czas 2-10 minut więc to jest EZ
