### ISSUE TITLE
Ignore node_modules folder

### ISSUE THREAD

**Issue by gogo1704** [gogo1704/furry-bot#32]
Ogolnie przeczytałem na https://nodejs.dev/learn/ że generalnie nie powinno sie pushować node_modules na gita bo ten folder może być duży w zależności od rozmiaru projektu. To nie jest u nas problem i raczej wątpie żeby kiedykolwiek był ale robie issue żeby o tym pamiętać.

**Comment by BrzesiekGrydniak** [comment]
W sumie warte zapamiętania

**Comment by lufv** [comment]
Prawdopodobnie nie będziemy używać innych modułów i tak, nie?

**Comment by gogo1704** [comment]
> 
> 
> Prawdopodobnie nie będziemy używać innych modułów i tak, nie?

raczej bedziemy

**Comment by gogo1704** [comment]
juz usunołem node_modules w #44
