### ISSUE TITLE
Woda gazowana

### ISSUE THREAD

**Issue by lufv** [gogo1704/furry-bot#38]
Wygląda na to, że to działa w ten sposób, że kwas węglowy, który jest stworzony z wody i dwutlenku węgla jest bardzo niestabilny i ciągle się przemienia między kwas węglowy, a woda + dwutlenek węgla. Ostatecznie wygląda to w ten sposób, że woda i kwas węglowy to praktycznie to samo tylko, że przemieniają się w każdym momencie. Pozdrawiam, będę tu cały wieczór XD

**Comment by gogo1704** [comment]
Ur opinion is wrong

**Comment by lufv** [comment]
Nie wymyśliłem tego, pytałem osób, które są na chemii, więc...

**Comment by gogo1704** [comment]
they wrong

**Comment by lufv** [comment]
They not

**Comment by gogo1704** [comment]
cuz i say so

**Comment by lufv** [comment]
Ale to jest ogólnie bardzo ciekawy koncept

**Comment by lufv** [comment]
W zapisie to wygląda bodajże w ten sposób, że jak normalnie jest zapisywane H20 + CO2 -> H2CO3 to tutaj jest zapisywane H20 + CO2 <=> H2CO3, ponieważ to się ciągle zmienia.

**Comment by Kostiik** [comment]
ołów mniam

**Comment by lufv** [comment]
how dare you?!
