### ISSUE TITLE
spam command hard cap

### ISSUE THREAD

**Issue by gogo1704** [gogo1704/furry-bot#49]
Fajnie byloby dodać do komendy spam max wiadomosci ile moze wyslac (np 5).
Bedzię to bezpieczniejsze i nie będzie wywalać API spam errora

**Comment by Kostiik** [comment]
przecież wpisuje się ile wiadomości ma wysłać.
zobacz usage

**Comment by gogo1704** [comment]
> 
> 
> przecież wpisuje się ile wiadomości ma wysłać.
> zobacz usage

mi chodzi o takie hard max że nigdy nie wysle wiecej wiadomosci niz to max.
i tak wiem ze discord blokuje bota po 5 wiadomosciach ale to i tak fajnie byloby zaimplementowac

**Comment by lufv** [comment]
To już jest chyba w main, więc spoko.

**Comment by gogo1704** [comment]
nie jest -.-

**Comment by lufv** [comment]
No jest przecież. Jak dasz 10 wiadomości, to wyśle 5, poczeka chwilę, bo Discord i później kolejne 5. Chyba nie da się obejść zabezpieczenia discorda, ~~chyba, że nadanie pewnych permission botowi może pomóc.~~

**Comment by gogo1704** [comment]
no ale chodzi o to zeby dać hard cap

**Comment by lufv** [comment]
What do you mean?

**Comment by gogo1704** [comment]
Wstawic max liczbe ile mozna komus naspamic

**Comment by gogo1704** [comment]
Hardcoded 5 wiadomosci fc477d42d520e216de8eac1570470e520071caa1
