### ISSUE TITLE
spam.js better usage

### ISSUE THREAD

**Issue by gogo1704** [gogo1704/furry-bot#55]
Trzeba poprawic spam.js ze jak jakis argument jest niepoprawny to nie wypisuje "Number must be a number" XD tylko po prostu wypisuje usage.

Trzeba tez bardziej przetestowac rózne inputy bo czasami wywala unexpecter error

**Comment by lufv** [comment]
TODO; adresat spamu to ostatni mention w komendzie. 
Aktualnie jest to pierwszy mention i taka komenda `'spam @--[>-<---]>----------.+++.---. twoja stara @GogoFox 5` wysyła wiadomość do mnie z moją nazwą: `w sensie ja dostalem cos takiego '@--[>-<---]>----------.+++.---. twoja stara'`

**Comment by lufv** [comment]
Also:
![obraz](https://user-images.githubusercontent.com/43139327/109154669-8532ca80-7766-11eb-89d3-1f13e2885195.png)

**Comment by gogo1704** [comment]
to ma sens ponieważ:
`Usage: ;spam <message> <@ user> <number>`

dobrym rozwiązanie byloby zeby zamienic kolejnascia te rzeczy
np. `<@ user> <message> <number>`

**Comment by gogo1704** [comment]
znowu jakiegos goscia oznaczylem -.-

**Comment by lufv** [comment]
> 
> 
> to ma sens ponieważ:
> `Usage: ;spam <message> <@ user> <number>`
> 
> dobrym rozwiązanie byloby zeby zamienic kolejnascia te rzeczy
> np. `<@ user> <message> <number>`

To się wydaje bardziej intuicyjne faktycznie

**Comment by gogo1704** [comment]
Fixed in fc477d42d520e216de8eac1570470e520071caa1
