### ISSUE TITLE
index.js has to be run from / directory

### ISSUE THREAD

**Issue by lufv** [gogo1704/furry-bot#57]
To nie jest jakis duży problem, ale jak uruchamiasz node z innego dir niż /, np. 
`~/f/commands (activities)> node ../index.js`
to wtedy szuka wszystkiego w tym folderze: 
`Error: ENOENT: no such file or directory, scandir './commands'`.

Prawdopodobnie ez fix; w index.js trzeba dodac lokalizację index.js i ją używać jako pivot dla wszystkiego innego.

**Comment by gogo1704** [comment]
To powinno naprawić ten problem:
https://nodejs.org/api/process.html#process_process_chdir_directory

**Comment by gogo1704** [comment]
58d97e6f19115904c074b4aaf9641d4d146995b8

Fixed! <3
