### ISSUE TITLE
Unhandled promises

### ISSUE THREAD

**Issue by gogo1704** [gogo1704/furry-bot#8]
W wielu miejscach w kodzie potencjalnie może wywalić błąd (np. bot nie ma uprawnień do kanału). Nie ogarniam jeszcze jak najlepiej do tego podejść więc na razie się tym nie bawie.

**Comment by gogo1704** [comment]
Najprostszym rozwiązaniem wydaje się dodanie `.catch()` po każdym `send()` ale nie wiem czy chcemy kopiować to do każdej linijki `send()`

**Comment by Kostiik** [comment]
fixed, dodałem check for permissions w index.js
